### ISSUE TITLE
Wall thickness evaluation

### ISSUE THREAD

**Issue by vinamragehlot** [julienr/meshcut#19]
The idea is to get the thickness of the section shown in image. The vertical distance of planer cross-section lines to the next one. Is there a possibility to get it with mesh cut?

![00](https://user-images.githubusercontent.com/26214766/121871461-6e5bb800-cd04-11eb-9cc0-7a6fa76b881d.jpg)

**Comment by julienr** [comment]
I think you should be able to extract the blue lines forming your section using meshcut. But then to compute the vertical distance is something you'll have to implement yourself.
