### ISSUE TITLE
How to get slice as polygon

### ISSUE THREAD

**Issue by Harvie** [julienr/meshcut#2]
Hi! I want to use this to get list of lines representing intersection polygons at given STL/PLY layer height. So i can generate custom g-code based on that. How can i do it? I can't get mayavi working, but i don't even need that. I just need polylines.

Thanks in advance...

**Comment by julienr** [comment]
I'm not sure I understand the question correctly, but doesn't the example of using `meshcut.cross_section` in the [README](https://github.com/julienr/meshcut#usage) work ?

**Comment by Harvie** [comment]
Ah, sorrry. Got it working now. I was bit confused about removing the mayavi code from the example...

**Comment by julienr** [comment]
Great if it works !

**Comment by Harvie** [comment]
Yes! Awesome. I am working on https://github.com/vlachoudis/bCNC/issues/901 and i got bCNC to slice my first mesh :-)

![image](https://user-images.githubusercontent.com/276504/42542746-9b173baa-84a8-11e8-84e0-e8871782a676.png)

![image](https://user-images.githubusercontent.com/276504/42543599-d685f100-84ac-11e8-9cb9-7a48be86d79e.png)
